// export { default as About } from "./About";
// export { default as Award } from "./Award";
// export { default as Contact } from "./Contact";
// export { default as EarthRotate } from "./EarthRotate";
// export { default as Education } from "./Education";
// export { default as Experience } from "./Experience";
// export { default as Hero } from "./Hero";
// export { default as Project } from "./Project";
// export { default as Skill } from "./Skill";
